### ISSUE TITLE
Got verified but project still unknown

### ISSUE THREAD

**Issue by ThePsychedelicMan** [Cardano-NFTs/policyIDs#1128]
https://github.com/Cardano-NFTs/policyIDs/pull/839

This is my PR, my policies are the same as the one in cnft.io. I just copy pasted them. Can someone please guide me through what's the issue? I was so excited i got merged finally but now i just got sad again. Hope somebody can help me fix this.

Thanking you in advance.

**Comment by NationsADA** [comment]
Hey mate, i also got merged but the project on yhe NFTs is still unknown and the tick has not appeared yet? Did you find any solution?

**Comment by ThePsychedelicMan** [comment]
Hey buddy, how long has it been after you got merged? It appears after 2 hours. If it hasn't appeared after 5 hours there might be something wrong

**Comment by NationsADA** [comment]
Its been two days now. Can you take a look and help me probably?
https://github.com/Cardano-NFTs/policyIDs/blob/main/NationsADA

**Comment by ThePsychedelicMan** [comment]
This looks good, maybe submit a ticket or text on discord or keep tweeting at them, they might reply

**Comment by NationsADA** [comment]
Thanks for your time and the advice. At least now i know that i don't have something wrong.
