### ISSUE TITLE
Is this platform real?

### ISSUE THREAD

**Issue by dogesound** [Cardano-NFTs/policyIDs#1132]

**Comment by dogesound** [comment]
It seems like a "verified project" = "friends and acquaintances of the platform" when I look at issues with delayed pull requests.  Our goal is decentralization and openness and trustlessness, not "this project looks cool and verifiable in my opinion."  NFTs are a component of w3 and should not be at the mercy of middlemen.  I.e., verified = exists on IPFS.

**Comment by CNFT-io** [comment]
We are working on a solution for all! 

This is very labour heavy and we have a solution for you all :)
