### ISSUE TITLE
Someone verified MY nfts on their project before i could verify mine.

### ISSUE THREAD

**Issue by Fl4tl4nd** [Cardano-NFTs/policyIDs#1286]
This "project" has two NFT policies in the list that belong to another project.

https://github.com/Cardano-NFTs/policyIDs/commit/ab391fb99f517707769b96bbcb8e057a03cc34ca

67d7a65bcb029654860315e26678bd894f3c268e8675735a3530abb3
23584c64008e60bb945ff000a9e60d45af84c10eda28a2d920f45df5

Please remove them.

**Comment by ThePsychedelicMan** [comment]
See buddy I got my policies from nft-maker.io and I paid for them! I can show you the transaction proof and the metadata. I do not understand how we can get the same policies. Maybe text the website support from where you minted your nfts and ask them. Also dm me on Twitter ill need to see your policy proof.

**Comment by Fl4tl4nd** [comment]
seems like we have the same policy as shown on the chain exporer
https://cardanoassets.com/23584c64008e60bb945ff000a9e60d45af84c10eda28a2d920f45df5
other two are there as well. Closing this.
