### ISSUE TITLE
Merged = Verified?

### ISSUE THREAD

**Issue by Kucibuk** [Cardano-NFTs/policyIDs#1332]
When my commit was merged to the nft:main, should i expect the checkmark on the marketplace?

**Comment by biceppool** [comment]
Same thing happened to me. Merged but no checkmark. I went back and found an error in my JSON formatting and commited a valid version. Suggest checking your JSON formatting. I used https://jsonlint.com/ 
Hope that helps

**Comment by Kucibuk** [comment]
> Same thing happened to me. Merged but no checkmark. I went back and found an error in my JSON formatting and commited a valid version. Suggest checking your JSON formatting. I used https://jsonlint.com/
> Hope that helps

aaah foun invalid json. This sux, been waiting to find out that i worte it with mistake. Anyway thank you! It helped! Closing
