### ISSUE TITLE
Cardano Mushrooms still not verified after 6 days

### ISSUE THREAD

**Issue by rizwanssyed** [Cardano-NFTs/policyIDs#1497]
I am wondering why my project is not yet verified even after I did every thing as advised. Could you please take some time and look into it? Thanks.

**Comment by CNFT4Humanity** [comment]
Cardano Catz still not verified after two weeks...
https://github.com/Cardano-NFTs/policyIDs/pull/713

**Comment by rizwanssyed** [comment]
> Cardano Catz still not verified after two weeks...
> #713

Well Stale does it himself and has no one else to assist him in this. So, maybe he did not find time to re-check yet. I am sure once he has some time he will address this. But, yes, it feels annoying that we have to wait for so long. It is impacting the sales.

**Comment by andblake22** [comment]
> > Cardano Catz still not verified after two weeks...
> > #713
> 
> Well Stale does it himself and has no one else to assist him in this. So, maybe he did not find time to re-check yet. I am sure once he has some time he will address this. But, yes, it feels annoying that we have to wait for so long. It is impacting the sales.

Hey rizwan, would you mind helping me? how do I create a policy ID? Also, how do I create a project? I would really  appreciate the help :)

**Comment by rizwanssyed** [comment]
@itsmestale Could you please approve our project. It's been over a week now. Thanks.
