### ISSUE TITLE
#1253 still not verified! Please help

### ISSUE THREAD

**Issue by Slatters** [Cardano-NFTs/policyIDs#1630]
When will i be verified? i been waiting for 8-9 days now.
Also, how does my other projects get verified? do i need to do the same here or can i just list them?
thank you

**Comment by Slatters** [comment]
https://github.com/Cardano-NFTs/policyIDs/pull/1253

**Comment by CelDivision** [comment]
hi there. i am not an expert, but i followed your pull and your link and it really needs to follow the tutorial to the letter. remember you are trying to prove the validity of the project/works being yours
hope that helps

**Comment by Slatters** [comment]
Its great to hear from you Adam. What do you recommend me to include in there?

**Comment by CelDivision** [comment]
well when i go to your twitter theres no immediate evidence that you are in fact the owner of the works youre seeking to verify

**Comment by Slatters** [comment]
Is there anything else other than twitter that could be included?

**Comment by CelDivision** [comment]
i dont think so......the verification is done by a human by eye and they aint going to waste time trying to figure out the validity of of a pull.....our job is to make it as easy as possible for them to verify.....so try the twitter fix and let me know how you get on....i have one caught in limbo too and im trying to figure out why

**Comment by Slatters** [comment]
I appreciate all the support. i will try with the twitter and make a change. they really give hell to smaller artists. Hope you figure out your stuff out man!

**Comment by cardanomushrooms** [comment]
@CelDivision Could you take a look are pull request # 1596, please, and let me know if I have done it properly. Thank you in advance.

**Comment by Slatters** [comment]
you have a similar issue to me bro , give him some kind of evidence or some proof to your assets.
if you have twitter, copy the link to your pull request and tweet. if you have any other social media like discord or your website just put a link to it. you have shown no evidence of your self. Hope this helps. Adam is prob going to tell you the same thing he told me.
