### ISSUE TITLE
provide API to verify NFT ownership

### ISSUE THREAD

**Issue by jpollard-cs** [Cardano-NFTs/policyIDs#1635]
Hi sorry if this is not the right place for this, but for some reason I got banned from the Discord server.
I'd really like a way to be able to verify ownership of our NFTs so we can grant special roles in Discord, etc.. for folks who have purchased our NFTs. Since there's not a standard wallet like Metamask in the ETH ecosystem this is hard to do, but since you're the dominant player in the Cardano NFT space this would be a nice feature for you to add and I'd be happy to write a Discord bot that integrates with this API.

**Comment by CelDivision** [comment]
what discord server?

**Comment by jpollard-cs** [comment]
> what discord server?

cnftofficial
