### ISSUE TITLE
Long delay on pull request #1339

### ISSUE THREAD

**Issue by JakeAdlerWriter** [Cardano-NFTs/policyIDs#1636]
Please confirm whether or not you have all the prerequisite information to verify the project pull request #1339,

Repeated below.
Pull request #1339
{
"project": "The Complete Nemedian Trilogy",
"tags": [ 
    "Nemedian Trilogy",
    "Fantasy",
    "fantasy books",
    "vampire"
],
"policies": [
    "aedce57e22c06a804302ffbd40a217ec51eb589939f26293a14af6fb"
]
}
First CNFT ASSET of this project is named Bruja the Vampire
Fingerprint asset1s4sxpha67j6emwqfhvqp9dl7dzs63dxxupaghg

To prove that I am the legitimate author and creator of these NFTs and works (Jake Adler is my nom de plume), I have officially tweeted about this on my author account and pinned it here:
 https://twitter.com/JakeAdlerWriter/status/1438770699599073280?s=20
Policy also pinned on Facebook author page: https://www.facebook.com/nemediantrilogy/
Policy also pinned on Wordpress author account: https://wordpress.com/view/magickingdoms.wordpress.com

**Comment by CelDivision** [comment]
this is perfect. thanks for taking the time to share

**Comment by JakeAdlerWriter** [comment]
don't forget the open starter tilde at the beginning {

**Comment by JakeAdlerWriter** [comment]
After over 3 weeks of not getting this simple project verfication accepted, I'm looking into Tokhun.io and reminting there.
