### ISSUE TITLE
My pull request was closed without merging. Why?

### ISSUE THREAD

**Issue by cs224** [Cardano-NFTs/policyIDs#3091]
My pull request was closed without merging. Why?
https://github.com/Cardano-NFTs/policyIDs/pull/2923
There was no explanation so far.

Thanks!

**Comment by granada-pool** [comment]
I had the same issue

**Comment by EmaCada** [comment]
same here #2669

**Comment by javiergradiche** [comment]
+1 https://github.com/Cardano-NFTs/policyIDs/pull/3001

**Comment by GhostCastle** [comment]
Same here #2581 without reason ?

**Comment by MatiFalcone** [comment]
+1 #2588

**Comment by starter098** [comment]
Same[ #2975](https://github.com/Cardano-NFTs/policyIDs/pull/2975)

**Comment by Hazoz1987** [comment]
Same here #2778

**Comment by ADA4rt** [comment]
same #2814

**Comment by nftyousee** [comment]
Same here #2590

**Comment by plantacrypto** [comment]
Hello, my pull request was close without any comments or merge. #3012 P

**Comment by ABCardanoNFT** [comment]
Same #2408

**Comment by javiergradiche** [comment]
Hi to everyone with the same problem please check if your PR is containing an old `json` structure. 
I get my new PR approved using the new structure. Ensure you are defining an array at the top level, no matter if you only submit 1 project.

**Comment by npdemons** [comment]
Me too #3055

**Comment by plantacrypto** [comment]
> Hi to everyone with the same problem please check if your PR is containing an old `json` structure. I get my new PR approved using the new structure. Ensure you are defining an array at the top level, no matter if you only submit 1 project.

We made a new pull request, #3216,  taking this under consideration. Thanks @javiergradiche , we are waiting for a positive result

**Comment by GhostCastle** [comment]
> Hi to everyone with the same problem please check if your PR is containing an old `json` structure.
> I get my new PR approved using the new structure. Ensure you are defining an array at the top level, no matter if you only submit 1 project.
Hi, you mean changing the metadata of the NFTs or change the pull request json file ?

**Comment by JakeAdlerWriter** [comment]
The lack of smart contract implementation with NFTs, plus slow hand verification and closing pull requests without any explanation (same happened to me) has put me off ADA for now.  I'm just investing in BTC and ETH at the moment. Shame.

**Comment by javiergradiche** [comment]
> > Hi to everyone with the same problem please check if your PR is containing an old `json` structure.
> > I get my new PR approved using the new structure. Ensure you are defining an array at the top level, no matter if you only submit 1 project.
> > Hi, you mean changing the metadata of the NFTs or change the pull request json file ?

Changing the PR, not the metadata.

**Comment by cs224** [comment]
My issue was resolved when I resubmitted the pull request in the new format as indicated above. Good luck to everyone else!!
