### ISSUE TITLE
Why is my pull request failing to validate json validation?

### ISSUE THREAD

**Issue by Absoluteunitsnft** [Cardano-NFTs/policyIDs#3153]
I am trying to add another policy id to my project and failed once. I read that I might need to change the formatting so I did that as well and it still didn't work. How can I validate the JSON correctly? Thank you for your time here is my current pull request #3135

**Comment by ThianchaiNFT** [comment]
Try my format below.

[
{
"project": "YourProject1",
"tags": ["Name of your project1 "],
"policies": [
"policy1",
"policy2"
]
},
{
"project": "YourProject2",
"tags": ["Name of your project2 "],
"policies": [
"Project2Policy1",
"Project2Policy2",
"Project2Policy3",
"Project2Policy4",
"Project2Policy5"
]
}
]

**Comment by Absoluteunitsnft** [comment]
I just changed my format again and had the same problem
