### ISSUE TITLE
Json in the same structure described in "Read"

### ISSUE THREAD

**Issue by bananada1097** [Cardano-NFTs/policyIDs#3345]
Hello, I put it in the same structure described on the home page under "Read"

_Originally posted by @bananada1097 in https://github.com/Cardano-NFTs/policyIDs/issues/3340#issuecomment-964160975_

**Comment by ECariele** [comment]
@bananada1097 where can I find this Readme file?

**Comment by bananada1097** [comment]
@ECariele  https://github.com/Cardano-NFTs/policyIDs#readme
