### ISSUE TITLE
Dear Contributor, please use the new JSON format in the Readme file on the home page.

### ISSUE THREAD

**Issue by LordPanda10** [Cardano-NFTs/policyIDs#3693]
"Dear Contributor, please use the new JSON format in the Readme file on the home page."

_Originally posted by @TomStray in https://github.com/Cardano-NFTs/policyIDs/issues/3566#issuecomment-970406942_

I just need another look at what I have and if it's the tags in my json file that need to be removed. And I'd like to know if I'm going to need to open a new pull request to do this.

**Comment by dazzy1975** [comment]
I've got the same message myself, but can't seem to find the read me file that it mentions.

**Comment by LordPanda10** [comment]
It's a hassle for sures, especially when nothing gets explained well enough before they close your pull request and prevent you from trying to fix it. But hopefully someone addresses this issue so we can get an answer.

**Comment by LordPanda10** [comment]
I found the issue, they don't allow using the Tags in your code. The head dev stale needs to update the support page for adding NFTs because in his video he shows adding the tags as if it's still an option. So basically if you want to get accepted, do not add Tags.

**Comment by dazzy1975** [comment]
Thanks for letting me know, I’ll sort that out.
Cheers 😁
