### ISSUE TITLE
nfts show unknown project after verifying

### ISSUE THREAD

**Issue by vsnftcreations** [Cardano-NFTs/policyIDs#657]
My nfts show unknown project after my project has been verified

**Comment by vsnftcreations** [comment]
resolved

**Comment by GabriNFabio** [comment]
how did you solve this?

**Comment by vsnftcreations** [comment]
I did not solve it. Haha

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
