### ISSUE TITLE
Anniebellnft #6583 Pull Request

### ISSUE THREAD

**Issue by anniebellnft** [Cardano-NFTs/policyIDs#6665]
Hi,

My project policy number was successfully merged and verified but its not showing up on my listings on the cnft.io Marketplace. 

They are still showing as unknown project. 

Are there additional steps or processes I need to complete?  

Thank you,

Annie

**Comment by Wobot22** [comment]
Is it solved? I'm waiting for 3 days...

**Comment by anniebellnft** [comment]
@Wobot22 not yet I'm still waiting too
