### ISSUE TITLE
Verification Issue

### ISSUE THREAD

**Issue by 39riffat** [Cardano-NFTs/policyIDs#880]
Hi sir,
My name is Tonoy.My server name rwiat-nfts.
Sir I submitted my pull request for verification 9 days ago.But not verified yet.

If possible please let me know how many days it would take.

**Comment by Koelie1984** [comment]
Same

**Comment by 39riffat** [comment]
What should we do now...?

**Comment by CNFT4Humanity** [comment]
Same...

**Comment by JakeAdlerWriter** [comment]
I'm sure (just 24 hours in waiting) that CNFT.IO realise that if they don't respond quicker in the near future, that other CNFT websites will spring up and CNFT.IO will quickly lose its popularity.  Although some are involved in creating their own NFT's, they must have this in mind about establishing a good reputation.  Hopefully this delay will resolve soon.  I have my first NFT waiting for project verification.  It's my CNFT, so I can sell it elsewhere (eventually).  Keep patient for now folks, which is all we can do (for the time being). :)
