### ISSUE TITLE
Verification Problem

### ISSUE THREAD

**Issue by suwunk31** [Cardano-NFTs/policyIDs#891]
Please, verify the policyID pull request: suwunk31/Cardatoons. it's been more than 10 days not verified 😔

**Comment by Koelie1984** [comment]
Same here

**Comment by suwunk31** [comment]
@Koelie1984 the verification process is random, not in order of number and time of pull request

**Comment by Koelie1984** [comment]
Are you sure?

**Comment by suwunk31** [comment]
try to look at pull requests > tab closed and sort date

**Comment by suwunk31** [comment]
there's something new yesterday, registered a policyID but it's been verified

**Comment by Koelie1984** [comment]
yeah big projects getting verified

**Comment by suwunk31** [comment]
Will be bad news, if like that. I hope that after the smart contract there will be a website like cnft io that can accept small projects, because if not, I'm afraid, many people will leave cardano nft.

**Comment by suwunk31** [comment]
at least, to be fair in verification must be sorted by queue time.

**Comment by CardanoPets** [comment]
Still waiting too? I’m not even sure I’ve done any of this right. So hard to find good help.

**Comment by CNFT4Humanity** [comment]
Priority is given to rich youtubers who are selling their NFTs for 50 ADA.

**Comment by ThePsychedelicMan** [comment]
> Priority is given to rich youtubers who are selling their NFTs for 50 ADA.

What happened with your verification request, what's with the policy being locked?

**Comment by CNFT4Humanity** [comment]
> > Priority is given to rich youtubers who are selling their NFTs for 50 ADA.
> 
> What happened with your verification request, what's with the policy being locked?

The request is still pending...

**Comment by DearDisaster** [comment]
In the video tutorial, I think he said there's only one person doing verifications. I'd be willing to help out if anyone in charge is willing to let me.

**Comment by RichAnimals** [comment]
yeah..it make new creator hard to create interesting NFT.
